Rani 01 patch 1
rkpagadala/school pull request #4
Opened 2023-08-18 16:46 UTC by Rani-01

updated database with sqlalchemy and sqllite3
used class objects for student details
removed assert function.

First install packages sqlalchemy and unittest using commands
pip install sqlalchemy
pip install unittest
in terminal
first run school_management.py and then test.py using commands
python school_management.py
python test.py

2023-08-21 06:07 UTC, rkpagadala requested changes

2023-08-21 06:07 UTC, rkpagadala commented on school_management.py
> +        connector.close()
remove

2023-08-21 06:07 UTC, rkpagadala commented on school_management.py
> +def update_record(admission_no, new_data):
add as staticmethod to student class

2023-08-21 06:07 UTC, rkpagadala commented on test.py
> +    def setUp(self):
create test data and connect

2023-08-21 06:07 UTC, rkpagadala commented on test.py
> +    def tearDown(self):
delete test data

2023-08-21 06:07 UTC, rkpagadala commented on test.py
> +        Base.metadata.drop_all(engine)
no drop all

2023-08-21 06:07 UTC, rkpagadala commented on test.py
> +if __name__ == '__main__':
new line

2023-08-27 05:05 UTC, merged

2023-09-09 05:01 UTC, Rani-01 commented on school_management.py
> +        connector.close()
removed

2023-09-09 05:01 UTC, Rani-01 commented on test.py
> +if __name__ == '__main__':
done

2023-09-09 05:02 UTC, Rani-01 commented on test.py
> +        Base.metadata.drop_all(engine)
removed drop all